### PR TITLE
Feature/milestone 04

### PR DESCRIPTION
**Pull request by carlosveigadev**
- Add logic folder and its files;
- Add operate and calculation logic;
- Import calculation to App.js.

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @carlosveigadev  :wave:

__You've done well so far :clap:__

**_Major highlights:_**
- Well composed readme :+1: 
- Descriptive PR title and summary :100: 

__However, some changes are required before this milestone can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] You're required to import `operate.js` in the `calculate.js` module. You should then use this module to perform the basic operations of your calculator.
- [x] Kindly include the modifier (turning the number into a percentage based number, e.g. 95 % == .95) function in your `operate.js` module.

That's it! 



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Comment by carlosveigadev** [comment]
Hi @teekaytech, thanks for the review.
I improved the code as suggested.

**Review by SpaYco — APPROVED** [review]
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by carlosveigadev** [comment]
@Spayco, thanks for the review.

**Pull request closed without merging**
